platform :ios, '13'
use_modular_headers!

target 'MarketKitExample' do
  pod 'MarketKit.swift', :path => '../'
  pod 'HsToolKit.swift', git: 'https://github.com/baboaisystem/lib_hstool_swift'

  pod 'SnapKit'
end
